apiVersion: apps/v1
kind: Deployment
metadata:
  name: sflow
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: sflow
spec:
  selector:
    matchLabels:
      app: sflow
  replicas: 1
  template:
    metadata:
      labels:
        app: sflow
    spec:
      containers:
        - name: sflow
          image: sflow/prometheus
          args:
            # - "-Dsnmp.ifname=yes"
            - "-Dscript.file=/sflow-scripts/bgp.js"
            - "-Dbgp.start=yes"
            - "-Dgeo.country=/sflow-geo/GeoLite2-Country.mmdb"
            - "-Dgeo.asn=/sflow-geo/GeoLite2-ASN.mmdb"

          volumeMounts:
            - mountPath: /sflow-geo
              name: sflow-geo
            - mountPath: /sflow-scripts
              name: sflow-scripts
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 100Mi
          #   limits:
          #     cpu: 100m
          #     memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 8008
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8008
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 8008
              name: http
            - containerPort: 6343
              protocol: UDP
              name: sflow
      restartPolicy: Always
      volumes:
        - name: sflow-geo
          persistentVolumeClaim:
            claimName: sflow-geo
        - name: sflow-scripts
          configMap:
            name: sflow-scripts
