apiVersion: v1
kind: Service
metadata:
  name: traefik-api
  namespace: traefik
spec:
  selector:
    app.kubernetes.io/instance: traefik-ingress
    app.kubernetes.io/name: traefik
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
