apiVersion: apps/v1
kind: Deployment
metadata:
  name: sporten
  namespace: default
  labels:
    app: sporten
spec:
  selector:
    matchLabels:
      app: sporten

  template:
    metadata:
      labels:
        app: sporten
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
      - name: sporten
        image: ghcr.io/maishond/basicfit-ding:main
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
          - name: MAISAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: maisauth_client_id
                name: sporten
          - name: MAISAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: maisauth_client_secret
                name: sporten
          - name: MAISAUTH_DISCOVERY_URL
            valueFrom:
              secretKeyRef:
                key: maisauth_discovery_url
                name: sporten
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: uri
                name: sporten-app
          - name: BASIC_CARD_NUMBER
            valueFrom:
              secretKeyRef:
                key: basic_card_number
                name: sporten
          - name: BASIC_DEVICE_ID
            valueFrom:
              secretKeyRef:
                key: basic_device_id
                name: sporten
          - name: BASE_URL
            value: https://sport.isaensting.nl
        ports:
        - containerPort: 3000
          name: http
      restartPolicy: Always