apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: maishond.nl
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`maishond.nl`)
      services:
        - kind: Service
          name: maishond-site
          namespace: default
          port: http

    - kind: Rule
      match: Host(`media.maishond.nl`)
      services:
        - kind: Service
          name: jellyfin
          namespace: media
          port: http

    - kind: Rule
      match: Host(`request.maishond.nl`)
      services:
        - kind: Service
          name: jellyseerr
          namespace: media
          port: http

    - kind: Rule
      match: Host(`leuk-achtergrondje.maishond.nl`)
      services:
        - kind: Service
          name: achtergrondje
          namespace: default
          port: 80

    - kind: Rule
      match: Host(`aap.maishond.nl`)
      services:
        - kind: Service
          name: rhel-aap
          namespace: traefik
          port: 443
          scheme: https
          serversTransport: insecure

    - kind: Rule
      match: Host(`monkey.maishond.nl`)
      services:
        - kind: Service
          name: rhel-aap
          namespace: traefik
          port: 443
          scheme: https
          serversTransport: insecure
      middlewares:
        - name: monkey-redirect
          namespace: traefik

    - kind: Rule
      match: Host(`meet.maishond.nl`)
      services:
        - kind: Service
          name: jitsi-jitsi-meet-web
          namespace: jitsi
          port: 80

    - kind: Rule
      match: Host(`chat.maishond.nl`)
      services:
        - kind: Service
          name: cynisch
          namespace: matrix
          port: 80

  tls:
    secretName: maishond.nl-prod-tls
