apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: staging.matrix.maishond.nl
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`chat.staging.matrix.maishond.nl`)
      services:
        - kind: Service
          name: cynisch
          namespace: matrix-staging
          port: 80

  tls:
    secretName: staging-matrix-maishond.nl-prod-tls
