apiVersion: apps/v1
kind: Deployment
metadata:
  name: thelounge
  namespace: default
  labels:
    app: thelounge
spec:
  selector:
    matchLabels:
      app: thelounge
  replicas: 0
  template:
    metadata:
      labels:
        app: thelounge
    spec:
      # securityContext:
      #   runAsNonRoot: false
      # runAsUser: 0
      # runAsGroup: 0
      #   fsGroup: 0

      containers:
        - name: thelounge
          image: ghcr.io/thelounge/thelounge:4.4.3
          livenessProbe:
            tcpSocket:
              port: 9000
          readinessProbe:
            httpGet:
              path: /
              port: 9000
          ports:
            - containerPort: 9000
              name: http
          volumeMounts:
            - name: thelounge-data
              mountPath: /var/opt/thelounge

      volumes:
        - name: thelounge-data
          persistentVolumeClaim:
            claimName: thelounge-data

      restartPolicy: Always
