# apiVersion: v1
# kind: Service
# metadata:
#   name: hookshot
#   namespace: matrix
# spec:
#   selector:
#     app: hookshot
#   type: ClusterIP
#   ports:
#     - name: homeserver
#       protocol: TCP
#       port: 9993
#       targetPort: 9993
#     - name: webhook
#       protocol: TCP
#       port: 9000
#       targetPort: 9000
#     - name: metrics
#       protocol: TCP
#       port: 9002
#       targetPort: 9002
