apiVersion: v1
kind: Service
metadata:
  name: cynisch
  namespace: matrix-staging
spec:
  selector:
    app: cynisch
  type: ClusterIP
  ports:
    - name: cynisch
      protocol: TCP
      port: 80
      targetPort: http
