kind: ConfigMap
apiVersion: v1
metadata:
  name: cynisch-config
  namespace: matrix
data:
  config.json: |
    {
      "defaultHomeserver": 0,
      "homeserverList": [
        "maishond.nl",
        "vdaa.me"
      ],
      "allowCustomHomeservers": false,

      "featuredCommunities": {
        "openAsDefault": false,
        "spaces": [
        ],
        "rooms": [
        ],
        "servers": ["maishond.nl"]
      },

      "hashRouter": {
        "enabled": false,
        "basename": "/"
      }
    }
