apiVersion: apps/v1
kind: Deployment
metadata:
  name: cynisch
  namespace: matrix
  labels:
    app: cynisch
spec:
  selector:
    matchLabels:
      app: cynisch
  replicas: 1
  template:
    metadata:
      labels:
        app: cynisch
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: cynisch
          image: ghcr.io/maishond/cynisch:ac4bdcab66b1a27ba7d841a6ed94975dba81341a
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/config.json
              readOnly: true
              subPath: config.json
      volumes:
        - name: config
          configMap:
            name: cynisch-config
            defaultMode: 0444
            items:
              - key: config.json
                path: config.json
      restartPolicy: Always
