apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinny
  namespace: matrix
  labels:
    app: cinny
spec:
  selector:
    matchLabels:
      app: cinny
  replicas: 1
  template:
    metadata:
      labels:
        app: cinny
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: cinny
          image: ghcr.io/maishond/cynisch:latest
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/config.json
              readOnly: true
              subPath: config.json
      volumes:
        - name: config
          configMap:
            name: cinny-config
            defaultMode: 0444
            items:
              - key: config.json
                path: config.json
      restartPolicy: Always
