apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cluster.boem
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  # middlewares:
  #   - name: internal-whitelist
  routes:
    - kind: Rule
      match: Host(`alerts.cluster.boem`)
      middlewares:
        - name: internal-whitelist
      services:
        - kind: Service
          name: alertmanager-operated
          namespace: monitoring
          passHostHeader: true
          port: 9093

    - kind: Rule
      match: Host(`traefik.cluster.boem`)
      middlewares:
        - name: internal-whitelist
      services:
        - name: traefik-api
          namespace: traefik
          port: 9000

    # - kind: Rule
    # match: Host(`longhorn.cluster.boem`)
    # middlewares:
    #   - name: internal-whitelist
    # services:
    #   - name: longhorn-frontend
    #     namespace: longhorn-system
    #     port: 80

    - kind: Rule
      match: Host(`prometheus.cluster.boem`)
      middlewares:
        - name: internal-whitelist
      services:
        - name: prometheus-operated
          namespace: monitoring
          port: http-web

    # - kind: Rule
    #   match: Host(`postgres.cluster.boem`)
    #   middlewares:
    #     - name: internal-whitelist
    #   services:
    #     - name: postgres-operator-ui
    #       namespace: postgres
    #       port: 80

    - kind: Rule
      match: Host(`mailslurper.cluster.boem`)
      middlewares:
        - name: internal-whitelist
      services:
        - name: fake-smtp-server-ui
          namespace: mailslurper
          port: 4436

    - kind: Rule
      match: Host(`mailslurper.cluster.boem`) && PathPrefix(`/adminm`)
      middlewares:
        - name: mailslurper-stripprefix
      services:
        - name: fake-smtp-server-admin
          namespace: mailslurper
          port: 4437

    - kind: Rule
      match: Host(`dns.cluster.boem`)
      services:
        - name: pdns-admin
          namespace: default
          port: 80

    - kind: Rule
      match: Host(`pgadmin.cluster.boem`)
      services:
        - name: pgadmin4
          namespace: default
          port: 5050

    - kind: Rule
      match: Host(`netbox.cluster.boem`)
      services:
        - name: netbox
          namespace: default
          port: 8000

    # - kind: Rule
    #   match: Host(`courier.kratos.cluster.boem`)
    #   services:
    #     - name: kratos-courier
    #       namespace: ory
    #       port: 80

  tls:
    secretName: cluster.boem-certs
