# apiVersion: v1
# kind: Service
# metadata:
#   name: llama
#   namespace: default
# spec:
#   selector:
#     app: llama
#   ports:
#     - name: http
#       protocol: TCP
#       port: 11434
#       targetPort: http
