# apiVersion: v1
# kind: Service
# metadata:
#   name: sting-site
#   namespace: default
# spec:
#   selector:
#     app: sting-site
#   type: ClusterIP
#   sessionAffinity: None
#   sessionAffinityConfig:
#     clientIP:
#       timeoutSeconds: 10800
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80
